// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sigillum.Arcavis.Infrastructure.Persistence.EfCore.Context;

#nullable disable

namespace Sigillum.Arcavis.Infrastructure.Persistence.EfCore.Migrations
{
    [DbContext(typeof(ArcavisContext))]
    [Migration("20260305140235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sigillum.Arcavis.Core.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("CREATED_BY")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<bool>("IS_DELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnOrder(5);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<DateTime>("UPDATED_AT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("UPDATED_BY")
                        .HasColumnType("uuid")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("Sigillum.Arcavis.Core.Domain.Users.User", b =>
                {
                    b.OwnsMany("Sigillum.Arcavis.Core.Domain.Users.Emails.Email", "_emails", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("ID")
                                .HasColumnOrder(0);

                            b1.Property<DateTime>("CREATED_AT")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnOrder(2);

                            b1.Property<Guid?>("CREATED_BY")
                                .HasColumnType("uuid")
                                .HasColumnOrder(1);

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EMAIL");

                            b1.Property<bool>("IS_DELETED")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnOrder(5);

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("IS_VERIFIED");

                            b1.Property<DateTime>("UPDATED_AT")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnOrder(4);

                            b1.Property<Guid?>("UPDATED_BY")
                                .HasColumnType("uuid")
                                .HasColumnOrder(3);

                            b1.Property<Guid?>("USER_ID")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("EmailAddress")
                                .IsUnique();

                            b1.HasIndex("USER_ID");

                            b1.ToTable("USER_EMAIL", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("USER_ID");
                        });

                    b.OwnsMany("Sigillum.Arcavis.Core.Domain.Users.Passwords.Password", "_passwords", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("ID")
                                .HasColumnOrder(0);

                            b1.Property<DateTime>("CREATED_AT")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnOrder(2);

                            b1.Property<Guid?>("CREATED_BY")
                                .HasColumnType("uuid")
                                .HasColumnOrder(1);

                            b1.Property<bool>("IS_DELETED")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnOrder(5);

                            b1.Property<string>("PasswordHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PASSWORD_HASH");

                            b1.Property<DateTime>("UPDATED_AT")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnOrder(4);

                            b1.Property<Guid?>("UPDATED_BY")
                                .HasColumnType("uuid")
                                .HasColumnOrder(3);

                            b1.Property<Guid?>("USER_ID")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("USER_ID");

                            b1.ToTable("USER_PASSWORD", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("USER_ID");
                        });

                    b.Navigation("_emails");

                    b.Navigation("_passwords");
                });
#pragma warning restore 612, 618
        }
    }
}
